environment: production
chdir: /home/azureuser/apps/grapeapi/current/
address: 127.0.0.1
user: azureuser
port: 8000
pid: /home/azureuser/apps/grapeapi/current/tmp/pids/thin.pid
rackup: /home/azureuser/apps/grapeapi/current/config.ru
log: /home/azureuser/apps/grapeapi/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true